name: Deploy Catalog
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-catalog/**'
env:
  SPRING_APPS_SERVICE: ${{ secrets.SPRING_APPS_SERVICE }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  KEY_VAULT: ${{ secrets.KEY_VAULT }}
  CATALOG_SERVICE_APP: catalog-service

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-catalog
    steps:
      - uses: actions/checkout@v3
      - name: Install Pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
      # - name: Set up Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.SUBSCRIPTION }}
      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push Docker image using Buildpacks
        run: |
          pack build ${{ secrets.ACR_SERVER }}/acme-fitness-store-bp/cataglog:${{ github.sha }} --builder gcr.io/buildpacks/builder:v1 --path .
          docker push ${{ secrets.ACR_SERVER }}/acme-fitness-store-bp/cataglog:${{ github.sha }}
